version: "3.9"

services:
    app:
        build: app/
        restart: always
        depends_on:
          - db
          - rmq
        networks:
          - network
      sber-test-bot:
        build: sber-test-bot/
        restart: always
        networks:
          - network

networks:
    network:
        {}