version: "3.9"

services:
  app:
    build: app/
    ports:
      - '80:80'
    tty: true
    restart: always
    networks:
      - network
  
  sber-test-bot:
    build: sber-test-bot/
    restart: always
    networks:
      - network

networks:
  network:
      {}